### PR TITLE
Add Seg#succ

### PR DESCRIPTION
**Pull request by frodsan**
Any chance to add a method to return next segment without capture?

I tried #next but it's a reserved keyword.

### CODE REVIEW

**Comment by soveran** [comment]
I'll check this one tonight, but it looks like a good addition.

**Comment by soveran** [comment]
I will change the name and I'll probably change the implementation a bit, because I think we can provide two methods `extract` and `retract`. I'll work on this now.

**Comment by soveran** [comment]
Released as `1.1.0`. I'm working on the refactoring, and I'm wondering if you are using this: `seg.consume("foo/bar")`. The reason I ask is because I think it may be better to disallow matching multiple segments at once, so you would be forced to do `seg.consume("foo")` and later `seg.consume("bar")`. What do you think? I'm not using that form anywhere in my apps.

**Comment by frodsan** [comment]
Does that improve performance? I don't think I'm using that. Seg 2.x?

Can you create a branch with the refactor so I can do some tests? Thanks.

**Pull request merged**
